# Generated by Django 5.0.7 on 2024-08-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersFormsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name="Ім'я")),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(default='', max_length=10, verbose_name='Tel.')),
                ('answers', models.TextField(blank=True, null=True, verbose_name='Відповіді')),
                ('budget', models.TextField(blank=True, null=True, verbose_name='Бюджет')),
                ('language', models.TextField(verbose_name='Мова')),
            ],
        ),
    ]
