# Generated by Django 5.0.7 on 2024-08-03 13:38

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(verbose_name="Ім'я замовника")),
                ('company_name', models.TextField(verbose_name='Назва компанії,агенції,корпорації')),
                ('user_emoji', models.ImageField(upload_to='media_storage/reviews_img', verbose_name='Емодзі замовника')),
                ('rating', models.FloatField(verbose_name='Кількість зірок')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Контент')),
                ('language', models.CharField(choices=[('ua', 'Українська'), ('en', 'English'), ('hu', 'Magyar')], default='', max_length=20, verbose_name='Мова сайту')),
            ],
        ),
    ]
