# Generated by Django 5.0.3 on 2024-04-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.TextField()),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='media_storage/news_img')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
