# Generated by Django 5.0.3 on 2024-04-18 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='date',
            new_name='created_at',
        ),
    ]
