# Generated by Django 5.0.3 on 2024-04-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_date_new_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='language',
            field=models.TextField(choices=[('uk', 'Українська'), ('en', 'English')], default='uk'),
        ),
    ]
