# Generated by Django 5.0.3 on 2024-04-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.TextField()),
                ('project_name', models.TextField()),
                ('project_tools', models.TextField()),
                ('project_tasks', models.TextField()),
                ('project_deadline', models.TextField()),
                ('project_developers', models.TextField()),
                ('project_etaps', models.TextField()),
                ('bot_url', models.URLField()),
                ('image', models.ImageField(upload_to='media_storage/chatbot_cases')),
                ('video', models.FileField(upload_to='media_storage/chatbot_cases')),
            ],
        ),
    ]
