# Generated by Django 5.0.3 on 2024-04-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.TextField()),
                ('project_name', models.TextField()),
                ('project_tools', models.TextField()),
                ('project_tasks', models.TextField()),
                ('project_deadline', models.TextField()),
                ('project_developers', models.TextField()),
                ('project_etaps', models.TextField()),
                ('bot_url', models.URLField()),
                ('image', models.ImageField(upload_to='media_storage/chatbot_cases')),
                ('video', models.FileField(blank=True, upload_to='media_storage/chatbot_cases')),
            ],
        ),
        migrations.AlterField(
            model_name='chatbotcase',
            name='video',
            field=models.FileField(blank=True, upload_to='media_storage/chatbot_cases'),
        ),
    ]
