# Generated by Django 5.0.3 on 2024-04-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_chatbotcase_language_sitecase_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitecase',
            old_name='bot_url',
            new_name='site_url',
        ),
    ]
