# Generated by Django 5.0.7 on 2024-07-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_rename_bot_url_sitecase_site_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField(verbose_name='Назва проекту')),
                ('project_sphere', models.TextField(verbose_name='Ніша проекту')),
                ('project_tools', models.TextField(verbose_name='Інструменти розробки')),
                ('project_tasks', models.TextField(verbose_name='Завдання')),
                ('project_deadline', models.TextField(verbose_name='Дедлайн ')),
                ('project_developers', models.TextField(verbose_name='Виконавці проекту')),
                ('project_etaps', models.TextField(verbose_name='Етапи роботи')),
                ('site_url', models.URLField(verbose_name='Посилання на проект')),
                ('project_type', models.CharField(choices=[('chat_bot', 'Телеграм-бот'), ('web_site', 'Сайт'), ('design', 'Дизайн')], default='', max_length=25, verbose_name='Категорія проекту')),
                ('image', models.ImageField(upload_to='media_storage/case_img')),
                ('video', models.FileField(blank=True, null=True, upload_to='media_storage/case_video')),
                ('language', models.TextField(choices=[('ua', 'Українська'), ('en', 'English'), ('hu', 'Magyar')], default='')),
                ('slug', models.SlugField(blank=True, default='', unique=True, verbose_name='Slug сторінки')),
            ],
        ),
        migrations.DeleteModel(
            name='ChatbotCase',
        ),
        migrations.DeleteModel(
            name='SiteCase',
        ),
    ]
