# Generated by Django 5.0.7 on 2024-08-13 22:14

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_delete_chatbotcase_delete_sitecase'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='look_for',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Переглянути (сайт,чат-бот) + посилання'),
        ),
        migrations.AlterField(
            model_name='case',
            name='project_type',
            field=models.CharField(choices=[('chat_bot', 'Телеграм-бот'), ('web_site', 'Сайт'), ('design', 'Дизайн'), ('mobile_app', 'Мобільний додаток')], default='', max_length=25, verbose_name='Категорія проекту'),
        ),
    ]
