# Generated by Django 5.0.7 on 2024-08-13 22:18

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_look_for_alter_case_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='site_url',
        ),
        migrations.AlterField(
            model_name='case',
            name='project_developers',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Виконавці проекту'),
        ),
        migrations.AlterField(
            model_name='case',
            name='project_etaps',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Етапи роботи'),
        ),
        migrations.AlterField(
            model_name='case',
            name='project_name',
            field=models.TextField(verbose_name='Назва проекту/компанії/підприємства'),
        ),
        migrations.AlterField(
            model_name='case',
            name='project_sphere',
            field=models.TextField(verbose_name='Ніша/сфера проекту'),
        ),
        migrations.AlterField(
            model_name='case',
            name='project_tasks',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Завдання'),
        ),
        migrations.AlterField(
            model_name='case',
            name='project_tools',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Інструменти розробки'),
        ),
        migrations.AlterField(
            model_name='case',
            name='project_type',
            field=models.CharField(choices=[('chat_bot', 'Телеграм-бот'), ('web_site', 'Сайт'), ('design', 'Дизайн'), ('mobile_app', 'Мобільний додаток')], default='', max_length=25, verbose_name='Категорія/тип проекту проекту'),
        ),
    ]
