"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./page.module.scss";
import './globals.scss'
import StarBackground from "@/app/[locale]/components/star-bg/StarBackground";
import {useState} from "react";
import Cookie from "@/app/[locale]/components/cookie/Cookie";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
interface RootLayoutProps{
    children: React.ReactNode,
    params: {
        locale: string,
    }
}
export default function RootLayout({
                                       children,
                                       params: {locale}
                                   }: Readonly<RootLayoutProps>)
{
    const [cookieConfirmed, setCookieConfirmed] = useState<boolean>(false);
    const handleCookieConfirmation = () => {
        setCookieConfirmed(true);
    };
  return (
      <html lang={locale}>
    <head>
        <title>Y.K Agency</title>
        <link rel="icon" href="/logo-btn.ico" />
        <meta name='Charity' content='Charity' />
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-654D9MSXCY"></script>
        <script
            dangerouslySetInnerHTML={{
                __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-654D9MSXCY');
            `,
            }}
        />
    </head>
      <body className={inter.className}>
      {/*<StarBackground />*/}
        {children}
      {!cookieConfirmed && <Cookie onConfirm={handleCookieConfirmation} />}
      </body>
    </html>
  );
}
